name: arisannusantara
description: "Manajemen Arisan Mudah, Cepat & Aman."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  cloud_firestore: ^6.0.3
  firebase_core: ^4.2.0
  flutter_staggered_grid_view: ^0.7.0
  firebase_crashlytics: ^5.0.3
  firebase_auth: ^6.1.1
  google_sign_in: ^7.2.0

  # Riverpod
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  
  # Others
  cached_network_image: ^3.4.1
  freezed: ^3.2.3
  google_fonts: ^6.3.2
  go_router: ^16.2.4
  shared_preferences: ^2.5.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

  # Riverpod
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/background/
    - assets/images/brands/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/brands/launcher_icon.jpg"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false